#!/bin/bash
APP="$1"; IMAGE="$2"

read -d '' runner <<'EOF'
#!/bin/bash

set -e
export HOME=/app
for file in \$HOME/.profile.d/*; do source \$file; done
hash -r
cd \$HOME

circusd circus.ini
EOF

set -e

id=$(docker run -i -a stdin $IMAGE /bin/bash -c "test -f /app/circus.ini")
docker attach $id
if [ $(docker wait $id) -ne 0 ]; then
    echo "-----> Skipping Circus ..."
    exit 0
fi

echo "-----> Injecting Circus ..."

id=$(echo "$runner" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /start && /app/.heroku/python/bin/pip install circus")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
